Repository DeterminateSystems/nix-installer, pull requests merged in 2023-09, with the labels that each got.

#618 Readme cutificiation
  README.md
Labels: documentation

#623 Uninvert EnableOwnership logic
  src/action/macos/enable_ownership.rs
Labels: MacOS

#626 Check for file existence before attempting to open it
  src/action/base/create_file.rs
  src/action/base/create_or_insert_into_file.rs
  src/planner/linux.rs
  src/planner/ostree.rs
  src/planner/steam_deck.rs
Labels: upload to s3

#631 Fix uninstall instructions
  README.md
Labels: documentation

#620 Make nix.conf changes deterministic
  Cargo.lock
  Cargo.toml
  src/action/base/create_file.rs
  src/action/base/create_or_insert_into_file.rs
  src/action/base/create_or_merge_nix_config.rs
  src/action/base/mod.rs
  src/action/common/place_nix_configuration.rs
  src/action/mod.rs
  src/planner/mod.rs
  tests/fixtures/linux/linux.json
  tests/fixtures/linux/steam-deck.json
  tests/fixtures/macos/macos.json
Labels: upload to s3

#635 Support user-defined diagnostics attribution
  README.md
  flake.lock
  flake.nix
  src/action/mod.rs
  src/diagnostics.rs
  src/planner/linux.rs
  src/planner/macos.rs
  src/planner/mod.rs
  src/planner/ostree.rs
  src/planner/steam_deck.rs
  src/settings.rs
Labels: upload to s3

#641 Release v0.12.0
  Cargo.lock
  Cargo.toml
  flake.lock
  flake.nix
  tests/fixtures/linux/linux.json
  tests/fixtures/linux/steam-deck.json
  tests/fixtures/macos/macos.json
Labels: upload to s3
