Repository DeterminateSystems/nix-installer, pull requests merged in 2023-02, with the labels that each got.

#217 Verify the apfs volume doesn't already exist before trying to create it
  src/action/darwin/create_apfs_volume.rs
  src/action/darwin/enable_ownership.rs
  src/action/darwin/mod.rs
  src/action/mod.rs
  src/settings.rs
Labels: MacOS

#188 init-less install
  .dockerignore
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  flake.nix
  nix/check.nix
  nix/tests/container-test/default.nix
  nix/tests/container-test/default/Dockerfile
  nix/tests/vm-test/default.nix
  src/action/base/setup_default_profile.rs
  src/action/common/configure_init_service.rs
  src/action/common/configure_nix.rs
  src/action/common/mod.rs
  src/action/common/place_channel_configuration.rs
  src/action/darwin/create_fstab_entry.rs
  src/action/darwin/kickstart_launchctl_service.rs
  src/action/darwin/mod.rs
  src/action/mod.rs
  src/lib.rs
  src/planner/darwin/multi.rs
  src/planner/linux/multi.rs
  src/planner/linux/steam_deck.rs
  src/planner/mod.rs
  src/settings.rs
  tests/fixtures/darwin/darwin-multi.json
  tests/fixtures/linux/linux-multi.json
  tests/fixtures/linux/steam-deck.json
  tests/plan.rs
  tests/windows/test-wsl.ps1
Labels: upload to s3, Linux, Windows (WSL2)

#230 Release v0.2.0
  Cargo.lock
  Cargo.toml
  flake.nix
  tests/fixtures/darwin/darwin-multi.json
  tests/fixtures/linux/linux-multi.json
  tests/fixtures/linux/steam-deck.json
Labels: upload to s3

#231 release: only run one release action at a time
  .github/workflows/release-branches.yml
  .github/workflows/release-prs.yml
  .github/workflows/release-tags.yml
Labels: upload to s3

#229 Add 32 bit support
  .buildkite/pipeline.yml
  flake.nix
  nix-installer.sh
  src/planner/mod.rs
  src/settings.rs
Labels: upload to s3, Linux

#237 Attempt to minimize steam deck display manager restart risk
  Cargo.lock
  src/action/linux/start_systemd_unit.rs
  src/planner/linux/steam_deck.rs
  tests/fixtures/linux/steam-deck.json
Labels: bug, upload to s3, Steam Deck

#244 Clarify stability
  CONTRIBUTING.md
  README.md
  src/cli/mod.rs
Labels: documentation

#249 Release v0.3.0
  Cargo.lock
  Cargo.toml
  flake.nix
  tests/fixtures/linux/linux.json
  tests/fixtures/linux/steam-deck.json
  tests/fixtures/macos/macos.json
  tests/windows/test-wsl.ps1
Labels: upload to s3

#253 Enable deleting users and groups on Mac
  nix/tests/container-test/default/Dockerfile
  nix/tests/vm-test/default.nix
  src/action/base/add_user_to_group.rs
  src/action/base/create_group.rs
  src/action/base/create_user.rs
  src/action/base/mod.rs
  src/action/base/setup_default_profile.rs
  src/action/common/create_users_and_groups.rs
  src/lib.rs
  tests/fixtures/linux/linux.json
  tests/fixtures/linux/steam-deck.json
  tests/fixtures/macos/macos.json
Labels: MacOS

#267 Improve permissions checking when dealing with existing files
  src/action/base/create_file.rs
  src/action/base/create_or_insert_into_file.rs
  src/action/common/configure_shell_profile.rs
  src/action/mod.rs
Labels: upload to s3
