Repository DeterminateSystems/nix-installer, pull requests merged in 2023-03, with the labels that each got.

#298 Use `launchctl load -w` on macOS
  src/action/common/configure_init_service.rs
Labels: upload to s3

#297 Detect WSL1 and error
  src/planner/linux.rs
  src/planner/mod.rs
Labels: upload to s3

#246 Cure APFS/Fstabs on Mac
  src/action/common/configure_init_service.rs
  src/action/macos/bootstrap_apfs_volume.rs
  src/action/macos/bootstrap_launchctl_service.rs
  src/action/macos/create_apfs_volume.rs
  src/action/macos/create_fstab_entry.rs
  src/action/macos/create_nix_volume.rs
  src/action/macos/enable_ownership.rs
  src/action/macos/encrypt_apfs_volume.rs
  src/action/macos/kickstart_launchctl_service.rs
  src/action/macos/mod.rs
  src/action/macos/unmount_apfs_volume.rs
  src/os/darwin.rs
  src/planner/macos.rs
  tests/fixtures/macos/macos.json
Labels: upload to s3

#319 Support busybox user/group modification, more informational errors
  Cargo.lock
  Cargo.toml
  src/action/base/add_user_to_group.rs
  src/action/base/create_group.rs
  src/action/base/create_user.rs
  src/action/common/create_users_and_groups.rs
  src/action/mod.rs
Labels: upload to s3

#332 Use rustls-tls-native-roots
  Cargo.lock
  Cargo.toml
Labels: upload to s3

#339 Update zshrc, not zshenv
  README.md
  src/action/common/configure_shell_profile.rs
Labels: upload to s3

#375 Make shell profile locations chosen by planner
  src/action/common/configure_nix.rs
  src/action/common/configure_shell_profile.rs
  src/planner/linux.rs
  src/planner/macos.rs
  src/planner/mod.rs
  src/planner/steam_deck.rs
  tests/fixtures/linux/linux.json
  tests/fixtures/linux/steam-deck.json
  tests/fixtures/macos/macos.json
Labels: bug, Steam Deck

#376 Use retry strategy after diskutil create
  src/action/macos/create_nix_volume.rs
Labels: bug, upload to s3, MacOS
