Repository DeterminateSystems/nix-installer, pull requests merged in 2023-01, with the labels that each got.

#144 BUGFIX(?): Resolve a steam deck system unit ordering bug after update
  src/planner/linux/steam_deck.rs
Labels: bug

#170 upload_s3: provide git ish as argument
  upload_s3.sh
Labels: upload to s3

#168 Release v0.0.1
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  flake.nix
  tests/fixtures/darwin/darwin-multi.json
  tests/fixtures/linux/linux-multi.json
  tests/fixtures/linux/steam-deck.json
Labels: upload to s3

#191 Add `(nix:$name)` as a prefix to the bash prompt
  src/action/common/place_nix_configuration.rs
Labels: upload to s3

#202 upload_s3: improve tags handling
  .github/workflows/release-branches.yml
  .github/workflows/release-prs.yml
  .github/workflows/release-tags.yml
  upload_s3.sh
Labels: upload to s3

#215 Use a UUID instead of volume name for fstab on Mac
  Cargo.lock
  Cargo.toml
  src/action/base/create_or_insert_into_file.rs
  src/action/darwin/create_fstab_entry.rs
  src/action/darwin/create_nix_volume.rs
  src/action/darwin/mod.rs
  tests/fixtures/darwin/darwin-multi.json
Labels: upload to s3

#216 Add a friendly top comment about `nix-installer.sh`
  nix-installer.sh
Labels: documentation
